### ISSUE TITLE
Could not decode to UTF-8?

### ISSUE THREAD

**Issue by Bo0oM** [SECFORCE/sparta#10]
How do I fix this?

>Traceback (most recent call last):
>  File "/home/bo0om/soft/sparta/ui/view.py", line 706, in contextMenuServiceNamesTableView
>    self.controller.handleServiceNameAction(targets, actions, action)
>  File "/home/bo0om/soft/sparta/controller/controller.py", line 314, in handleServiceNameAction
>    self.runCommand(tool, tabtitle, ip[0], ip[1], ip[2], command, getTimestamp(True), outputfile, self.view.createNewTabForHost(ip[0], tabtitle, restoring))
>  File "/home/bo0om/soft/sparta/controller/controller.py", line 498, in runCommand
>    textbox.setProperty('dbId', QVariant(str(self.logic.addProcessToDB(qProcess)))) # database id for the process is stored so that we can retrieve the widget later (in the tools tab)
>  File "/home/bo0om/soft/sparta/app/logic.py", line 402, in addProcessToDB
>    self.db.commit()
>  File "/home/bo0om/soft/sparta/db/database.py", line 47, in commit
>    session.commit()
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/scoping.py", line 114, in do
>    return getattr(self.registry(), name)(*args, **kwargs)
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 656, in commit
>    self.transaction.commit()
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 314, in commit
>    self._prepare_impl()
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 298, in _prepare_impl
>    self.session.flush()
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1583, in flush
>    self._flush(objects)
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1654, in _flush
>    flush_context.execute()
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 331, in execute
>    rec.execute(self)
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 475, in execute
>    uow
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 64, in save_obj
>    table, insert)
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 558, in _emit_insert_statements
>    execute(statement, params)
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1449, in execute
>    params)
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1584, in _execute_clauseelement
>    compiled_sql, distilled_params
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1698, in _execute_context
>    context)
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1691, in _execute_context
>    context)
>  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 331, in do_execute
>    cursor.execute(statement, parameters)
>sqlalchemy.exc.ProgrammingError: (ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. u'INSERT INTO db_tables_process (display, pid, name, tabtitle, hostip, port, protocol, command, starttime, outputfile, status, closed) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' ('True', '0', 'ftp-default', 'ftp-default (21/tcp)', '192.168.1.66', '21', 'tcp', u'hydra -s 21 -C ./wordlists/ftp-default-userpass.txt -u -o "/tmp/sparta-4Tolxp-running/ftpdefault/20150115133122-ftp-default-5.9.80.212-21.txt" -f 5.9.80.212 ftp', '15 \xd0\xaf\xd0\xbd\xd0\xb2 2015 13:31:22', '/tmp/sparta-4Tolxp-running/ftpdefault/20150115133122-ftp-default-5.9.80.212-21', 'Waiting', 'False')

**Comment by st3r30byt3** [comment]
Thanks for the bug report. We will look into it as high priority. Could you provide any other info as to what actions you were taking (it seems that you right-clicked to check default ftp credentials), had you ran other tools before, what OS you were on, 32/64 bit, etc? Note that we highly recommend you run SPARTA from Kali Linux.

**Comment by Bo0oM** [comment]
I'm doing any act
Example:
Click add host
http://i.imgur.com/xjY8U56.png
192.168.1.1, add to scope
http://i.imgur.com/9LJCmbG.png

>Linux ferrari 3.12-kali1-amd64 #1 SMP Debian 3.12.6-2kali1 (2014-01-06) x86_64 GNU/Linux
>java version "1.7.0_65"
>OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-2~deb7u1)
>OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

**Comment by st3r30byt3** [comment]
Thank you! We think we identified the problem (we are using ascii instead of unicode in several places) but just to be sure and if you don't mind answering:
- Could you post the output of "lsb_release -a"?
- Could you confirm that you are using elixir 0.7.1-1 and sqlalchemy 0.7.8-1?
- Could you post the full output of the first error you get (probably when you add hosts)?

**Comment by Bo0oM** [comment]
lsb_release -a:
>LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1->amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core->4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security->4.1-noarch
>Distributor ID:	Debian
>Description:	Debian GNU/Linux Kali Linux 1.0.9
>Release:	Kali Linux 1.0.9
>Codename:	n/a

sqlalchemy.__version__ 
'0.7.8'

 elixir.__version__ 
'0.7.1'

[+] Creating temporary files..
[+] Wordlist was created/opened: /tmp/sparta-viPMfT-tool-output/sparta-usernames.txt
[+] Wordlist was created/opened: /tmp/sparta-viPMfT-tool-output/sparta-passwords.txt
[+] Loading settings file..
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-2~deb7u1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
Traceback (most recent call last):
  File "/home/bo0om/soft/sparta/ui/view.py", line 375, in callAddHosts
    self.controller.addHosts(self.adddialog.textinput.text(), self.adddialog.discovery.isChecked(), self.adddialog.nmap.isChecked())
  File "/home/bo0om/soft/sparta/controller/controller.py", line 181, in addHosts
    self.runStagedNmap(iprange, runHostDiscovery)
  File "/home/bo0om/soft/sparta/controller/controller.py", line 552, in runStagedNmap
    self.runCommand('nmap','nmap (stage '+str(stage)+')', str(iprange), '', '', command, getTimestamp(True), outputfile, textbox, discovery, stage, stop)
  File "/home/bo0om/soft/sparta/controller/controller.py", line 498, in runCommand
    textbox.setProperty('dbId', QVariant(str(self.logic.addProcessToDB(qProcess)))) # database id for the process is stored so that we can retrieve the widget later (in the tools tab)
  File "/home/bo0om/soft/sparta/app/logic.py", line 402, in addProcessToDB
    self.db.commit()
  File "/home/bo0om/soft/sparta/db/database.py", line 47, in commit
    session.commit()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/scoping.py", line 114, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 656, in commit
    self.transaction.commit()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 314, in commit
    self._prepare_impl()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 298, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1583, in flush
    self._flush(objects)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1654, in _flush
    flush_context.execute()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 331, in execute
    rec.execute(self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 475, in execute
    uow
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 64, in save_obj
    table, insert)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 558, in _emit_insert_statements
    execute(statement, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1449, in execute
    params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1584, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1698, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1691, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 331, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings. u'INSERT INTO db_tables_process (display, pid, name, tabtitle, hostip, port, protocol, command, starttime, outputfile, status, closed) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' ('True', '0', 'nmap', 'nmap (stage 1)', '192.168.0.1', '', '', u'nmap -T4 -sV -sT -p T:80,443 192.168.0.1 -oA /tmp/sparta-43LyuF-running/nmap/20150115153712-nmapstage1', '15 \xd0\xaf\xd0\xbd\xd0\xb2 2015 15:37:12', '/tmp/sparta-43LyuF-running/nmap/20150115153712-nmapstage1', 'Waiting', 'False')

**Comment by st3r30byt3** [comment]
Thanks Dmitry. We fixed this and we'll push it in the next commit, hopefully today. We had to change Kali's language to Russian to troubleshoot it :)

**Comment by Bo0oM** [comment]
Everything works! Excellent software, thank you for your help, I will follow the development!
