### ISSUE TITLE
Kali Rolling in Windows 10

### ISSUE THREAD

**Issue by lgrayjunior** [SECFORCE/sparta#101]
Does anyone have a step by step list of commands to run on the Kali from the Windows App Store to get Sparta working?  I have looked up every guide I can find and it seems I always hit some failure on either Sparta or Nmap or other programs.

**Comment by xpelican** [comment]
Honestly while those Subsystems are a super cool idea on paper, myself and a whole lot of people I know just kept reporting so many bugs and incompatability problems that I don't trust them for anything other than menial tasks anymore.

Even running a VM, which are considered much more well-tested you're going to run into a lot of  buggy situations - and this goes especially true for most pentesting tools. Unfortunately, most of the programs used in penetration testing aren't the most well-tested or versatile, and they will start giving you weird errors and unintended results when the slightest thing is out of the ordinary.

I know this isn't the answer you want to hear, but if you're going to be doing pentests, I seriously recommend running a native Linux box. You'll feel better for it.

**Comment by lgrayjunior** [comment]
Thank you very much for the reply.  It's more than sufficient to tell me I am wasting my time (again) with Microsoft attempts to catch up with Linux (As if they ever will).
