### ISSUE TITLE
Error after installing Sparta using "git clone".

### ISSUE THREAD

**Issue by vonvy** [SECFORCE/sparta#103]
After installing all the requirements for the Sparta program, I have encountered an issue. Here is the output after trying to start Sparta using sudo privileges.

>Traceback (most recent call last):
  File "./sparta.py", line 29, in <module>
    from app.logic import *
  File "/home/aud/sparta/app/logic.py", line 19, in <module>
    from app.auxiliary import *
  File "/home/aud/sparta/app/auxiliary.py", line 14, in <module>
    import os, sys, urllib2, socket, time, datetime, locale, webbrowser, re, requests	# for webrequests, screenshot timeouts, timestamps, browser stuff and regex
ImportError: No module named requests

After this, it simply ends. I am using Zorin OS. Which is based off of Ubuntu 18.04. I know it is not Kali but Ubuntu should work, at least what I feel.

**Comment by dkomando** [comment]
I had the same issue. 
While I have Python3 installed the Python3 packages (pip3, pip3 install requests & python3-requests) didn't work for me.

Here is what worked for me:
sudo apt install python-requests

Hope that helps you out.

**Comment by vonvy** [comment]
Problem solved, thank you @dkomando

**Comment by st3r30byt3** [comment]
We've ported SPARTA to Python3 and PyQt5. It should run on the latest Kali.

Just install the dependencies as detailed in the README file.

You can get it from the dev branch here:
https://github.com/SECFORCE/sparta/tree/dev

If you find any bugs, please create another issue and we'll have a look asap.
