### ISSUE TITLE
Error while saving screenshots

### ISSUE THREAD

**Issue by VasilyKaiser** [SECFORCE/sparta#104]
Saving screenshots should be slowed down, it seems like it's trying to save a big number of screenshots at same time.
This is picture of errors I got, and 0 screenshot pictures were saved.
![Screenshot_20190712_200516](https://user-images.githubusercontent.com/50267052/61171932-d23b3c00-a543-11e9-8886-22e879cbaa3d.png)

**Comment by st3r30byt3** [comment]
We've ported SPARTA to Python3 and PyQt5. It should run on the latest Kali.

Just install the dependencies as detailed in the README file.

You can get it from the dev branch here:
https://github.com/SECFORCE/sparta/tree/dev

If you find any bugs, please create another issue and we'll have a look asap.
