### ISSUE TITLE
Should switch to Python 3

### ISSUE THREAD

**Issue by rhertzog** [SECFORCE/sparta#106]
Python 2.x will no longer be supported by their upstream developers in 2020. Thus Debian developers are actively removing Python 2 support in Debian Testing with the goal of getting rid of Python 2 in Debian 11 (bullseye).

Kali is tracking Debian Testing and is thus affected by this. As part of this process, Debian already entirely removed python-elixir (as there's no Python 3 port I believe) which broke sparta in Kali. We reintroduced the package in Kali for now but you should now seriously consider to switch sparta to Python 3...

FWIW this is tracked in https://gitlab.com/kalilinux/packages/sparta/issues/1 on the Kali side.

**Comment by st3r30byt3** [comment]
We've ported SPARTA to Python3 and PyQt5. It should run on the latest Kali.

For now it's in the dev branch and we will push to master once it has been tested a bit more.
https://github.com/SECFORCE/sparta/tree/dev
