### ISSUE TITLE
Should switch from PyQt4 to something newer based on Qt 5, likely Pyside 2

### ISSUE THREAD

**Issue by rhertzog** [SECFORCE/sparta#107]
Debian developers are actively trying to get rid of python-qt4 and at some point the package will disappear from Debian Testing and thus Kali. This will impact sparta in Kali.

It would be great if sparta could switch to something that's supported, such as Pyside 2 which is the Python library blessed by the Qt project (which is obviously based on Qt 5).

**Comment by st3r30byt3** [comment]
We've ported SPARTA to Python3 and PyQt5. It should run on the latest Kali.

For now it's in the dev branch and we will push to master once it has been tested a bit more.
https://github.com/SECFORCE/sparta/tree/dev
