### ISSUE TITLE
Code Request to get black/dark theme or background

### ISSUE THREAD

**Issue by zeeshanoscp** [SECFORCE/sparta#110]
Requesting the piece of code, that will change the white background into black/dark theme or background.

**Comment by CaptainStabs** [comment]
If you are using the Adwaita Dark theme on Debian, the GUI is automatically in dark theme

**Comment by st3r30byt3** [comment]
A bit late but here goes:

For black terminal background you can edit sparta.conf and set this line to:
tool-output-black-background=True.

For themes, like CaptainStabs said, depending on the OS you can get it in dark. For instance, in the latest Kali if you pick xfce by default SPARTA display in a dark theme.

**Comment by MidnightSeer** [comment]
Of course this doesn't work for me.  I have xfce kali and this setting is in my config.

Actually it seems to only color the terminal:

[GeneralSettings]
default-terminal=xfce4-terminal
enable-scheduler=True
enable-scheduler-on-import=False
max-fast-processes=10
max-slow-processes=10
screenshooter-timeout=15000
tool-output-black-background=True

![image](https://user-images.githubusercontent.com/21272239/82758383-42e1f480-9db4-11ea-9348-02eb74a7be70.png)

**Comment by st3r30byt3** [comment]
Hello. Sparta only has the setting for the terminal black background:
tool-output-black-background=True

This is what makes the terminal black in your screenshot.

We haven't explicitly coded a dark theme. However, in some desktop environments Sparta will automatically display in a dark theme.

On a recently downloaded Kali rolling with xfce, if you are using the Kali-Dark appearance setting (which was the default for me), Sparta displays as in my screenshot.
![dark-sparta](https://user-images.githubusercontent.com/8157586/82781978-86436e00-9e5b-11ea-94b1-acd51dfe0b4c.png)
