### ISSUE TITLE
list of commands

### ISSUE THREAD

**Issue by rowbot1** [SECFORCE/sparta#111]
Is there anyway to review what commands have been run for example the exact brute force command that was run?

**Comment by vinhnguyen154** [comment]
tất cả các lệnh của sparta để thu thập thông tin

**Comment by rowbot1** [comment]
can you be more specific?

**Comment by st3r30byt3** [comment]
Sorry for the delay. As Ross would say, we were on a break. :)

If you saved your project to a file, then you can open it with a tool like sqlitebrowser, go to the "process" tables and you will see for every process the command that was run along with other useful details such as start/end times, target host, etc.

Please reopen the issue if this doesn't answer your question.
