### ISSUE TITLE
Connot Run Sparta

### ISSUE THREAD

**Issue by geospus** [SECFORCE/sparta#113]
When trying to run sparta, it returns this result.
**_Traceback (most recent call last):
  File "sparta.py", line 29, in <module>
    from app.logic import *
  File "/usr/share/sparta/app/logic.py", line 19, in <module>
    from app.auxiliary import *
  File "/usr/share/sparta/app/auxiliary.py", line 14, in <module>
    import os, sys, urllib2, socket, time, datetime, locale, webbrowser, re, requests	# for webrequests, screenshot timeouts, timestamps, browser stuff and regex
ImportError: No module named requests_**

What I have to do?

**Comment by pratheep704** [comment]
Run python3 -m pip install requests

**Comment by laszloatoth** [comment]
Hi pratheep704,
I rab the suggested command but the situation didn't changed. What I did:
laci@sanyika:~$ python3 -m pip install requests
Please advise. The error message exactly:
laci@sanyika:~$ sparta
Traceback (most recent call last):
  File "sparta.py", line 29, in <module>
    from app.logic import *
  File "/usr/share/sparta/app/logic.py", line 19, in <module>
    from app.auxiliary import *
  File "/usr/share/sparta/app/auxiliary.py", line 14, in <module>
    import os, sys, urllib2, socket, time, datetime, locale, webbrowser, re, requests	# for webrequests, screenshot timeouts, timestamps, browser stuff and regex
ImportError: No module named requests

**Comment by st3r30byt3** [comment]
We've ported SPARTA to Python3 and PyQt5. It should run on the latest Kali.

Just install the dependencies as detailed in the README file.

You can get it from the dev branch here:
https://github.com/SECFORCE/sparta/tree/dev

If you find any bugs, please create another issue and we'll have a look asap.
