### ISSUE TITLE
cant install python elixir

### ISSUE THREAD

**Issue by ganyaaaa** [SECFORCE/sparta#114]
apt-get install python-elixir python-qt4 xsltproc
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-elixir is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Comment by ganyaaaa** [comment]
should i add some new source links?

**Comment by mok0** [comment]
Likely elixir is Python2 only and thus has been removed from the repos. If you want to continue to use Python2 you are on your own, i.e. install from upstream sources.

**Comment by st3r30byt3** [comment]
We've ported SPARTA to Python3 and PyQt5. It should run on the latest Kali.

Just install the dependencies as detailed in the README file.

You can get it from the dev branch here:
https://github.com/SECFORCE/sparta/tree/dev

If you find any bugs, please create another issue and we'll have a look asap.
