### ISSUE TITLE
 How to install  Python-elixir in Kali Linux 2020.1

### ISSUE THREAD

**Issue by lulzsecind** [SECFORCE/sparta#115]
sudo apt-get install python-elixir
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python-elixir

How I install Python-elixir in Kali version 2020.1

**Comment by poptart-alwayshungry** [comment]
_python-elixir_ depends on Python2; Python2 was deprecated at the beginning of 2020.  To download this package, go to https://pkgs.org/download/python-elixir.  I used the package for Debian 9/10.

*Note:*  To use SPARTA you'll also need to install _libqtcore4_.  Doing this will uninstall Wireshark, as Wireshark depends on _libqtcore5_.

**Comment by Sip147** [comment]
poptart-alwayshungry can you tell us more about installation because i can't get it to work

**Comment by poptart-alwayshungry** [comment]
1. Download `python-elixir` using the "Binary Package" link
2. Download `python-sqlalchemy` using the "Binary Package" link
3. Open Terminal to where you downloaded the two packages.  Normally it's `~/Downloads/`
4. `sudo dpkg -i *.deb`
5. `sudo apt install libqtcore4`
6. `sudo apt insall python-qt4`
From here you just follow the directions in _README.md_
7. `cd /usr/share`
8. `sudo git clone https://github.com/secforce/sparta.git`
9. `cd sparta`
10. `sudo chmod +x sparta`
11. `sudo mv sparta /usr/bin/`

Do note that screenshots will not function properly as `cutycapt` depends on `libqtcore5` as opposed to `libcoreqt4`

**Comment by DavidTik** [comment]
Hi, trying to follow the above recomended installation path, but cant get it to work
1 ok
2 ok
3 ok
4 ok
5 package 'python-qt4' has no installation candidate

Any suggestions to get the sparta working on kali linux 2020.1b

**Comment by poptart-alwayshungry** [comment]
You can find the `python-qt4` package using the same website linked above.

This is the link: https://pkgs.org/download/python-qt4
a) Under the "Debian 10" section, click the link for whichever processor you have.  
b) Find the **Binary Package** link under the **Downloads** section, highlight it, right click, and select "Open Link"
c) You will then be able to download the package (save it don't run it), navigate to the Downloads directory via the Terminal, and install it using Step 4 above.

**Comment by DavidTik** [comment]
Hi, thanks for the quick reply, but if i do this i get multiple dependency problems,..:
root@Kali:~# sudo dpkg -i *.deb
(Reading database ... 451786 files and directories currently installed.)
Preparing to unpack python-qt4_4.12.1+dfsg-2+b1_amd64.deb ...
Unpacking python-qt4 (4.12.1+dfsg-2+b1) over (4.12.1+dfsg-2+b1) ...
dpkg: dependency problems prevent configuration of python-qt4:
 python-qt4 depends on libqt4-dbus (>= 4:4.8.0-1~); however:
  Package libqt4-dbus is not installed.
 python-qt4 depends on libqt4-declarative (>= 4:4.8.0-1~); however:
  Package libqt4-declarative is not installed.
 python-qt4 depends on libqt4-designer (>= 4:4.8.0-1~); however:
  Package libqt4-designer is not installed.
 python-qt4 depends on libqt4-help (>= 4:4.8.0-1~); however:
  Package libqt4-help is not installed.
 python-qt4 depends on libqt4-network (>= 4:4.8.0-1~); however:
  Package libqt4-network is not installed.
 python-qt4 depends on libqt4-script (>= 4:4.8.0-1~); however:
  Package libqt4-script is not installed.
 python-qt4 depends on libqt4-scripttools (>= 4:4.8.0-1~); however:
  Package libqt4-scripttools is not installed.
 python-qt4 depends on libqt4-svg (>= 4:4.8.0-1~); however:
  Package libqt4-svg is not installed.
 python-qt4 depends on libqt4-test (>= 4:4.8.0-1~); however:
  Package libqt4-test is not installed.
 python-qt4 depends on libqt4-xml (>= 4:4.8.0-1~); however:
  Package libqt4-xml is not installed.
 python-qt4 depends on libqt4-xmlpatterns (>= 4:4.8.0-1~); however:
  Package libqt4-xmlpatterns is not installed.
 python-qt4 depends on libqtassistantclient4 (>= 4.6.3); however:
  Package libqtassistantclient4 is not installed.
 python-qt4 depends on libqtcore4 (>= 4:4.8.0-1~); however:
  Package libqtcore4 is not installed.
 python-qt4 depends on libqtgui4 (>= 4:4.8.0-1~); however:
  Package libqtgui4 is not installed.
 python-qt4 depends on sip-api-12.4; however:
  Package sip-api-12.4 is not installed.

dpkg: error processing package python-qt4 (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 python-qt4

**Comment by poptart-alwayshungry** [comment]
So you have two options from here, you can either:
a) download each of those packages from https://pkgs.org/ and run the `dpkg` command again, or 
b) Do `sudo apt install <package>` one by one to see if you can resolve the dependencies that way

**Comment by poptart-alwayshungry** [comment]
I suspect doing `sudo apt install libqtcore4` will fix most of your problems

**Comment by st3r30byt3** [comment]
We've ported SPARTA to Python3 and PyQt5. It should run on the latest Kali.

Just install the dependencies as detailed in the README file.

You can get it from the dev branch here:
https://github.com/SECFORCE/sparta/tree/dev

If you find any bugs, please create another issue and we'll have a look asap.
