### ISSUE TITLE
Kali Linux Support

### ISSUE THREAD

**Issue by Hirrszn** [SECFORCE/sparta#116]
Does Sparta work on the new Kali Linux 2020 or what is the last version on Kali Linux that Sparta is supported or works stable on?

Thanks,

**Comment by XxTheJanit0rxX** [comment]
Hello Friend,
I ran into the same issues trying to get Sparta to run until I found the fork. https://hakin9.org/legion-open-source-network-penetration-testing-tool/
If you are running Kali Linux a simple 'apt-get install legion -y ' will get you up and running.

I hope you find this helpful.

**Comment by st3r30byt3** [comment]
We've ported SPARTA to Python3 and PyQt5. It should run on the latest Kali.

Just install the dependencies as detailed in the README file.

You can get it from the dev branch here:
https://github.com/SECFORCE/sparta/tree/dev

If you find any bugs, please create another issue and we'll have a look asap.

**Comment by MahdiHedhli** [comment]
@Hirrszn @XxTheJanit0rxX you guys can also use Legion... it's in Kali's repos. We forked Sparta and upgraded it to Python3 and PyQt5 a while back when the project seemed dormant. 
More Info: 
[http://github.com/govanguard/legion](http://github.com/govanguard/legion)
[https://govanguard.com/legion/](https://govanguard.com/legion/)

Glad to see SecForce picked dev back up. Welcome any collaboration @st3r30byt3
