### ISSUE TITLE
some module missing to run sparta

### ISSUE THREAD

**Issue by laszloatoth** [SECFORCE/sparta#117]
Hi All,
Let me show you my error message:
laci@sanyika:~$ sparta
Traceback (most recent call last):
  File "sparta.py", line 29, in <module> from app.logic import *
  File "/usr/share/sparta/app/logic.py", line 19, in <module>  from app.auxiliary import *
  File "/usr/share/sparta/app/auxiliary.py", line 14, in <module> import os, sys, urllib2, socket, time, datetime, locale, webbrowser, re, requests	# for webrequests, screenshot timeouts, timestamps, browser stuff and regex
ImportError: No module named requests

I have already installed requests:
laci@sanyika:~$ python3 -m pip install requests
**Defaulting to user installation because normal site-packages is not writeable**
Requirement already satisfied: requests in /usr/local/lib/python3.8/site-packages (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/site-packages (from requests) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests) (1.25.8)

So please advise how to correct the mistake and run sparta app. Thanks.
KR,
  Laci.

**Comment by st3r30byt3** [comment]
We've ported SPARTA to Python3 and PyQt5. It should run on the latest Kali.

Just install the dependencies as detailed in the README file.

You can get it from the dev branch here:
https://github.com/SECFORCE/sparta/tree/dev

If you find any bugs, please create another issue and we'll have a look asap.
