### ISSUE TITLE
problems to run sparta

### ISSUE THREAD

**Issue by X-n3t** [SECFORCE/sparta#118]
I can't run sparta in new version of Parrot

![imagen](https://user-images.githubusercontent.com/52056830/78756657-717a4c00-797b-11ea-83e6-b63c4f2e4f5e.png)
Do you think in a new release?
Thanks.

**Comment by XxTheJanit0rxX** [comment]
Hello Friend,
I ran into the same issues trying to get Sparta to run until I found the fork. https://hakin9.org/legion-open-source-network-penetration-testing-tool/
If you are running Kali Linux a simple 'apt-get install legion -y ' will get you up and running.

I hope you find this helpful.

**Comment by X-n3t** [comment]
Thank you friend, in Parrot you need to do git clone and install manually some dependencies that aren't in requirements. And then execute startlegion.sh

**Comment by st3r30byt3** [comment]
We've ported SPARTA to Python3 and PyQt5. It should run on the latest Kali and hopefully Parrot if you install the requirements described in the README file.

You can get it from the dev branch here:
https://github.com/SECFORCE/sparta/tree/dev

If you find any bugs, please create another issue and we'll have a look asap.
