### ISSUE TITLE
Test suite failure with Python 3.5

### ISSUE THREAD

**Issue by 12358-dev** [SECFORCE/sparta#119]
It look like that sparta does not work fully with Python 3.5.3.when run on Debian stretch system you get the following failur

**Comment by st3r30byt3** [comment]
We've ported SPARTA to Python3 and PyQt5. It should run on the latest Kali.

Just install the dependencies as detailed in the README file.

You can get it from the dev branch here:
https://github.com/SECFORCE/sparta/tree/dev

If you find any bugs, please create another issue and we'll have a look asap.
