### ISSUE TITLE
[-] Import failed. Elixir library not found.  Try installing it with: apt install python-elixir

### ISSUE THREAD

**Issue by MrBlaze-web** [SECFORCE/sparta#121]
root@kali:~/Desktop/sparta# ls
app  CHANGELOG.txt  controller  db  doc  images  LICENSE  parsers  README.md  scripts  sparta  sparta.py  ui  wordlists
root@kali:~/Desktop/sparta# chmod u+x sparta.py
root@kali:~/Desktop/sparta# sparta.py
bash: sparta.py: command not found
root@kali:~/Desktop/sparta# /root/Desktop/sparta/sparta.py
[-] Import failed. Elixir library not found. 
Try installing it with: apt install python-elixir
root@kali:~/Desktop/sparta# ^C
root@kali:~/Desktop/sparta#

**Comment by st3r30byt3** [comment]
Hi. Please download the version in the dev branch, which doesn't use Elixir and uses Python3.

https://github.com/SECFORCE/sparta/tree/dev

**Comment by MrBlaze-web** [comment]
Ok thanks I can try
