### ISSUE TITLE
Request - Support for Parrot Security OS

### ISSUE THREAD

**Issue by hwac121** [SECFORCE/sparta#123]
At one time your app worked on Parrot Security OS, I did a brief tutorial on it and all my viewers loved the app. Most of them are Parrot Sec users since I do tutorials only with that distro. Now it no longer works on Parrot Sec. Now, I do realize it was not developed to work on Parrot Sec, but it would be great if you were to add support for Parrot Security OS, a Debian based distro along the lines of Ubuntu and/or Kali. Thanks for your time.

**Comment by st3r30byt3** [comment]
Hello. Thanks for doing the tutorial :)

Try grabbing the version from the dev branch. I just tried it on Parrot OS and it seemed to work after installing the requirements from the README file.

If that version doesn't work, feel free to post any bug information and we'll have a look.

**Comment by hwac121** [comment]
Thanks, I sure will try that out and pass that info on to my channel.

**Comment by X-n3t** [comment]
> At one time your app worked on Parrot Security OS, I did a brief tutorial on it and all my viewers loved the app. Most of them are Parrot

I have problems in parrot OS again. I tried with pipenv shell. I have afraid to broke the system for incompatibilities with python3

**Comment by X-n3t** [comment]
I tried with developer version(python3), but I have this problem:
![imagen](https://user-images.githubusercontent.com/52056830/84654522-a2dd3e00-af0f-11ea-81ef-53908ebfa700.png)

**Comment by st3r30byt3** [comment]
Yes, that is the way. The master version is still on python2. Please use the dev version for now.
