### ISSUE TITLE
python-elixir not found

### ISSUE THREAD

**Issue by pwned-cpp** [SECFORCE/sparta#127]
i run the program and it says "elixir library not found" i follow what it tells me to use "apt install python-elixir' but it says not found.

![Screenshot at 2020-08-16 00-29-51](https://user-images.githubusercontent.com/63930068/90323324-45855d80-df4f-11ea-99e4-9af40779695a.png)

**Comment by mark463** [comment]
same problem

**Comment by st3r30byt3** [comment]
Please use the dev version. Elixir is not required.

I will be pushing that version to main to avoid confusion.
