### ISSUE TITLE
Feature Request: Add automated dirb scan

### ISSUE THREAD

**Issue by curi0usJack** [SECFORCE/sparta#13]
You guys have made a killer tool and I am already using it on engagements. I love the integration with other tools, but was somewhat bummed by the fact that "Launch dirbuster" simply opens the tool. I'm no dirbuster expert, so maybe it can be done all via cli, but if http is detected, you could simply kick off a dirb scan and output the results to a window just like you do with nikto (that's an awesome integration by the way).

**Comment by st3r30byt3** [comment]
Hi curi0usJack! Thanks for the positive feedback! The main reason we chose not to run dirbuster or webslayer inside SPARTA is that depending on the web server and technologies you find you will probably want to use different wordlists. We thought we would be limiting the user too much. What we recommend is to add a tool in the configuration file which will run dirb/wfuzz with whatever wordlist you choose.

We posted in our blog about adding tools (http://sparta.secforce.com/2015/01/how-to-add-tools-and-configure-automated-attacks/) and you can always check SPARTA's help. :)

I hope this helps.

**Comment by curi0usJack** [comment]
Perfect. Next time I'll read the manual first!

Again - well done guys. :-)
