### ISSUE TITLE
Enhancement - Database Table Names

### ISSUE THREAD

**Issue by Ne0nd0g** [SECFORCE/sparta#15]
I recommend renaming the db_tables_nmap_host table to something more generic like db_tables_host. I would also do the same for all tables that have to potential to store other data which did not come from Nmap. This will increase the potential for expansion outside of using Nmap for host identification. Better to do it now then when the project is much farther along. A generic table name can allow for parsing other tool output (like Nessus) into the table without confusion.

**Comment by st3r30byt3** [comment]
Hey! Thanks for the suggestion. Since Nessus import is likely to be one of our next features, we will make those changes then (they had already been planned).
