### ISSUE TITLE
Use spaces instead of tabs

### ISSUE THREAD

**Issue by yasoob** [SECFORCE/sparta#17]
Is it possible to use spaces instead of tabs? Using tabs makes the code indent too much. Apart from that using spaces is a part of the Python style guide. 

Proposal:
------------

Convert tabs to 4 spaces.

**Comment by novist** [comment]
Spaces are standard for python so i think it would be a good idea. PEP8 all the things \o/

**Comment by st3r30byt3** [comment]
Not sure this is going to happen. At the moment, we would rather spend our time implementing new features and fixing bugs. Also, we are penetration testers and not programmers so chances are we are breaking many other Python standards. =) If you feel like doing it, feel free to submit a PR. :)
