### ISSUE TITLE
Try installing it with: apt-get install python-elixir (python-sqlalchemy 0.8+)

### ISSUE THREAD

**Issue by Bo0oM** [SECFORCE/sparta#18]
Errors:
[-] Import failed. Elixir library not found. 
Try installing it with: apt-get install python-elixir

But python-elixir installed. Import elixir leads to such error:
python
> import elixir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/pymodules/python2.7/elixir/__ init __.py", line 29, in <module>
    from elixir.entity import Entity, EntityBase, EntityMeta, EntityDescriptor, \
  File "/usr/lib/pymodules/python2.7/elixir/entity.py", line 17, in <module>
    from sqlalchemy.orm import MapperExtension, mapper, object_session, \
ImportError: cannot import name ScopedSession

FIx: 
python-sqlalchemy 0.8.0+, which changed the name of “ScopedSession” to
“scoped_session”

`pip install sqlalchemy==0.7.8` fixes the problem

**Comment by st3r30byt3** [comment]
Thanks for the reply. I'm closing this as I guess you meant to reply on the other thread. :)

**Comment by ozlatarski** [comment]
Hi, I'm having the same problem. Import elixir yields no error, however. Still getting the Import failed. Elixir library not found. Funny thing is apt-get install python-elixir yields: Unable to locate package python-elixir. I;m on a fresh Kali 2020.1 on an external hard drive. I've tried editing sparta.py a million ways to no avail. I've moved the sparta file to /bin and turned it executable with chmod +x sparta. When I run sparta in the terminal I get the above error. Any ideas?

**Comment by connected201** [comment]
hi, same problemm! OS kali

**Comment by ozlatarski** [comment]
Figured it out guys. Turns out python-elixir is python2. Kali 2020 versions (I assume probably 2019 as well) are python3. Thing is, you can downgrade, but you'll lose some stuff that is tied to python3. What NOONE seemed to say is that Sparta just has a different name in the newest Kali OS - it's called Legion. It even has more options...Wish you guys all the best. It was absolutely ridiculous how much research I had to do to come across this simple bit of info...

**Comment by aanne14** [comment]
You're a lifesaver! Thanks for your post I would probably have spent more time trying to figure out how to get Sparta to work on Kali 2020 and gone a bit crazy! Thank goodness i stumbled upon this post

**Comment by st3r30byt3** [comment]
We've pushed ported SPARTA to Python3 and PyQt5. It should run on the latest Kali. 

You can get it from the dev branch here:
https://github.com/SECFORCE/sparta/tree/dev

If you find any bugs, please create another issue and we'll have a look asap.
