### ISSUE TITLE
Issue with hydra using ftp module

### ISSUE THREAD

**Issue by osakaaa** [SECFORCE/sparta#25]
Hello there
I get an error message:

Hydra v7.5 (c)2013 by van Hauser/THC & David Maciejak - for legal purposes only
Hydra (http://www.thc.org/thc-hydra) starting at 2015-02-09 15:49:10

[ERROR] Unknown service: /home/user/dicts/dict.txt

while trying to bruteforce ftp credentials via hydra with the following options:
-Username - single name
- Password - password list from file
+ try blank password + try login as password + loop arround users + exit on first valid

**Comment by st3r30byt3** [comment]
Hi osakaaa. It seems that you forgot to enter the username.
If this is not the case feel free to send us the complete error message or ideally a screenshot so that we can troubleshoot.

**Comment by osakaaa** [comment]
Yep, looks like i left the Username field empty
Sorry

**Comment by matfix95** [comment]
'

**Comment by matfix95** [comment]
https://github.com/SECFORCE/sparta/issues/25#issue-57041984

> Hello there
> I get an error message:
> 
> Hydra v7.5 (c)2013 by van Hauser/THC & David Maciejak - for legal purposes only
> Hydra (http://www.thc.org/thc-hydra) starting at 2015-02-09 15:49:10
> 
> [ERROR] Unknown service: /home/user/dicts/dict.txt
> 
> while trying to bruteforce ftp credentials via hydra with the following options:
> -Username - single name
> 
> * Password - password list from file
> * try blank password + try login as password + loop arround users + exit on first valid


how did you fix the error???
