### ISSUE TITLE
Output nmap scan results to html

### ISSUE THREAD

**Issue by mcjon3z** [SECFORCE/sparta#26]
A nice feature enhancement would be to use something like xsltproc to convert nmap xml output into html and store it along with the other nmap output files in the output/nmap directory. This would allow for easy inclusion of all nmap scan results in the final penetration test report / supporting documentation as well as for reference in the audit workpapers.

Quick and dirty way would be to add it to the moveToolOutput function. I will be happy to play with it and submit PR.

**Comment by st3r30byt3** [comment]
Hey again! :) One of the things we are considering working on in the future is reporting functionality. However, it probably wouldn't rely (only) on converting nmap xml to html but would hopefully bring more meaningful information - maybe more vulnerability oriented. Unfortunately, we are still far from implementing that as we are first focusing on making SPARTA stable. I think simple html conversion is something we are not planning to do at the moment, sorry. Feel free to share any other ideas!

**Comment by mcjon3z** [comment]
Understood if reporting beyond directory output is the ultimate goal, which is exciting as well - base functionality is very strong as a tool in and of itself. 

I was just looking for something to bridge the gap between existing output and how I personally assemble tool output into a final report - for nmap, the html transforms seem to be the most readable for supporting workpapers IMHO.

I did manage to get a working HTML output as described with about 5 lines of code added on a fork - please feel free to look and grab if it looks like it will be of use. https://github.com/mcjon3z/sparta/tree/mcjon3z-nmap-enhancements

**Comment by st3r30byt3** [comment]
Since your 5 line solution is so simple we have included it in the next commit and credited you. :) Thanks.
