### ISSUE TITLE
Copy imported nmap scans into project file

### ISSUE THREAD

**Issue by mcjon3z** [SECFORCE/sparta#27]
Related to my previous post, another potential enhancement that comes to mind is to copy imported nmap scan files into the project file at the time of import (and possibly convert to html as well). This way the project file tool output directories remain a complete reference to the data in the project database.

As stated before, I'll be happy to play around with this as well and submit a PR.

Great tool, BTW - this project is looking to be one of the most useful tools in performing a penetration test that I have come across in a LOOONG time! Good job, gentlemen.

**Comment by st3r30byt3** [comment]
Hi Matthew! Thanks for the nice feedback.
Keeping a copy of the imported nmap is a good idea and shouldn't be difficult. Feel free to submit a PR. Know that we tend to push code ourselves and credit the contributors.

**Comment by st3r30byt3** [comment]
Done and will be included in the next commit. Thanks.
