### ISSUE TITLE
IP for LHOST

### ISSUE THREAD

**Issue by adamziaja** [SECFORCE/sparta#31]
Hi, there should be option for change default interface from where Sparta take IP address, because probably take IP from eth0 and there is no option to change this default value when Sparta generate resource file for MSF :).

**Comment by st3r30byt3** [comment]
Thanks for the feedback Adam. Good point. Actually, this happens outside of sparta in the smbenum.sh script where the first IP it finds is the chosen one.

MYIP=$(ifconfig | grep -Po '.*inet addr:\K[0-9.]*' | head -n1)

Maybe we can improve this in the script.

**Comment by adamziaja** [comment]
`MYIP=$(ifconfig $IFACE | awk -F'[: ]+' '/inet addr:/ {print $4}')`

**Comment by st3r30byt3** [comment]
We have included that code in smbenum.sh, will include it in our next commit and will credit you for this. Thanks. This is not ideal yet - as you still need to manually edit the script - but at least it provides an easier way around the problem. Probably when we release the settings menu (which we are working on now) we will add an "interface" setting.
