### ISSUE TITLE
Nikto output not saved completely

### ISSUE THREAD

**Issue by jljansen** [SECFORCE/sparta#33]
I'm using sparta on a standard Kali Linux install.

Nikto output files are not saved into a separate directory but stay in a temp folder called sparta-RANDOM-Running (within the project directory). The Nikto output files saved there are also not complete. Half of the finding and the summary are missing. Although as long as the tab of the Nikto scan is kept open the complete Nikto output is available there.
In the SQLite db if find a outputfile pointing to /tmp/sparta-RANDOM-running/20150325time-nikto-xx.xx.xx.xx-443 which has the same filename as in the project directory.

For other scripts I do not encounter this behavior.

**Comment by st3r30byt3** [comment]
Hi! Thanks for the feedback. We are looking into it.

**Comment by st3r30byt3** [comment]
We found the bug. This will be fixed in the next commit. Thanks again!
