### ISSUE TITLE
Enhancement - User-determined [OUTPUT] variable

### ISSUE THREAD

**Issue by CelloBin22** [SECFORCE/sparta#36]
Hi,

First off, absolutely love the tool!

Is there a way of changing the [OUTPUT] variable? For example, I don't necessarily require the date/time of the scan in the title of the output file.

Sorry if I've missed it and there already is!

**Comment by st3r30byt3** [comment]
Thanks for your feedback! When the [OUTPUT] tag is included in a command, we dynamically generate the filename with a timestamp. This is to ensure that everything gets stored correctly, that no file gets overwritten if you run a tool twice on the same host and to keep everything nice and organised.

You can of course either:
- Not include the [OUTPUT] tag and no output file will be created. The tool output will still get stored in the database.
- Or be crazy enough to edit the controller.py file where the filename is generated to generate whatever filename you want :)

Not sure if this helps but I hope it does.
