### ISSUE TITLE
Import list of hosts

### ISSUE THREAD

**Issue by nmalcolm** [SECFORCE/sparta#38]
It would be great if you could import a list of hosts instead of having to add them one by one. As SPARTA tries to save time, I think it's a must. :-)

Thanks.

**Comment by st3r30byt3** [comment]
Thanks! Yes, this is very high on our TODO but we've been a bit short on time lately and will be even more with the summer holidays approaching. 

In the meantime, you can import multiple IPs by using the same syntax supported by nmap. Eg: 192.168.1.1/24 or with spaces between IP addresses.

**Comment by phillips321** [comment]
As a quick fix for this could you just implement code that imports the targets.txt file as a list and replaces all the newline chars with spaces and then uses this (possibly long) string to populate the hosts field?

`mystring = mystring.replace('\n', ' ').replace('\r', '')`
```
cat targets.txt
192.168.0.2
192.168.0.4
192.168.1.200
192.168.2.30
==
192.168.0.2 192.168.0.4 192.168.1.200 192.168.2.30```
This will mean you only need one extra button on the add hosts widget that allows the user to point to the text file using QtGui.QFileDialog? Should be quick to implement, would do it myself if I could understand the project better, not really sure of the data flows and what functions/classes/objects calls what...

**Comment by st3r30byt3** [comment]
Don't worry. We have already implemented the 'Import hosts from file' functionality and it will be in the next release :)
