### ISSUE TITLE
Autorun Scheduler on NMap .XML import

### ISSUE THREAD

**Issue by HarmJ0y** [SECFORCE/sparta#4]
Is it possible to (either by default or through a settings option) to autorun the SchedulerSettings/PortActions when NMap data is imported, as opposed to only running the actions when a scan is initiated from Sparta? Would be killer!

**Comment by st3r30byt3** [comment]
Hi Will! Thanks for the feedback! That is definitely in our plans. Even today, during an assessment we were reminded the importance of that behaviour. It's just a matter of finding some time to implement it. ;) Please let us know of any other ideas/suggestions you may have. Btw, props for PowerUp!

**Comment by st3r30byt3** [comment]
It's implemented and will be in the next commit!

**Comment by HarmJ0y** [comment]
Awesome!
