### ISSUE TITLE
The session file  ./hydra.restore was written Type "Hydra -R" To resume session

### ISSUE THREAD

**Issue by MatthewHKnight** [SECFORCE/sparta#40]
Alright so im trying to work on releasing some videos for my YouTube channel of this awesome program however im facing a The session file  ./hydra.restore was written Type "Hydra -R" To resume session hang its i have a total of 7215 passwords in a file it keeps spamming 
The session file  ./hydra.restore was written Type "Hydra -R" To resume session
and its stuck at 7063 and just keeps saying The session file  ./hydra.restore was written Type "Hydra -R" To resume session now i cd to /cd /opt/sparta/
and typed Hydra -R says something about glibc detected **** hydra: double free or corruption 
Not sure what that's all about  been it shows that with some kinda  0x000007fb7f84dca80 then it spamms the terminal heh so not sure if this is a bug or what but im using the latest Kali Linux and the listed files from the website the apt-get install python-elixir and pt-get install ldap-utils rwho rsh-client x11-apps finger both installed.

Trying to brute force my SSH server on my level network.

![error](https://cloud.githubusercontent.com/assets/11364609/8847729/93f4beb0-30ff-11e5-8d7c-d1f97839af5e.png)
![error2](https://cloud.githubusercontent.com/assets/11364609/8847755/d99b1720-30ff-11e5-8bf3-55b2a87f4f9d.png)

**Comment by st3r30byt3** [comment]
Hi Matthew. Thanks for the feedback.
It seems to me that this could be a Hydra error. It looks as if hydra is crashing and so it is saving the hydra.restore file. We'll look into it whenever we have a bit of time but my gut feel tells me this may not be a problem in SPARTA.
Thanks!

**Comment by roelstorms** [comment]
I still have the same hydra double free error.
