### ISSUE TITLE
Enhancement - specify additional nmap parameters for staged scans in config file

### ISSUE THREAD

**Issue by mcjon3z** [SECFORCE/sparta#41]
Hi, Guys - I recently started using sparta pretty much exclusively on some live engagements, hence the slew of observations from me. It has been awesome but has given me some ideas for tweaks. 

Related to my previous comment regarding alternate config files, another idea that came to me was to move the rest of the logic for the staged nmap scans into the config file and out of the code to allow the entire nmap command (timing, service / OS identification, etc) to be modified within the config. I noted this in an external pentest in which stealth is of utmost priority and you don't want to use a timing of 4. Basically make the config file format for the staged scans to mirror the other tools instead of only specifying ports. This could further be modified to handle different levels of staged scans (some configs have 3 stages, some have 5, etc). I seem to remember stage levels being mentioned in another issue and cannot remember if it was ever implemented.

I may have some time to play with this one and shoot you a PR if you want - seems like this fix could be added without significantly changing the overall structure of the code and mangling your work.

Great job guys!

**Comment by mcjon3z** [comment]
Edit my previous comment - see open pull request https://github.com/SECFORCE/sparta/pull/23; Ne0nD0g beat me to this one!

**Comment by st3r30byt3** [comment]
Hey again :)

Thanks for the continued feedback: it IS appreciated.
We are back from holidays and are hoping to have a bit of time to keep improving SPARTA.

Ne0nD0g's (and your) suggestion for the staged nmap will be implemented in the next version.

Let us know of any other ideas / bugs.

Cya
