### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by wermaxta** [SECFORCE/sparta#42]
Hi i have problem with Sparta
when i type ./sparta or python sparta.py i got this 
[-] Import failed. Elixir library not found. 
Try installing it with: apt-get install python-elixir
so i type  apt-get install python-elixir and i got 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-elixir is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
so i don't know what is the problem.
my OS is 
Linux kali 3.18.0-kali3-686-pae #1 SMP Debian 3.18.6-1~kali2
Thank you.

**Comment by infosecgeek** [comment]
Try:
```bash
apt-get install pip
pip install elixir
```
Then try running Sparta again

**Comment by st3r30byt3** [comment]
Thanks infosecgeek. That's correct!
