### ISSUE TITLE
Moving the SQLLite file and trying to open on a different system throws error

### ISSUE THREAD

**Issue by lsuto** [SECFORCE/sparta#43]
"sqlalchemy.exc.OperationalError: (OperationalError) no such table: db_tables_nmap_host "SELECT \* FROM db_tables_nmap_host AS hosts WHERE 1=1 AND hosts.status!='down'" ()"

Is there a way to move the data/file in a way to get around this?

**Comment by st3r30byt3** [comment]
Sorry for the very late reply. We somehow missed this one. If this is still relevant, do you remember any other details? We would like to look into this.

Examples of useful details:
- did you move the .sprt file as well as the output folder?
- were you using Kali in both systems?
- did you have the same privileges on both systems?
- were you running the same version of SPARTA in both systems?

**Comment by mattwatkins93** [comment]
I get the exact same error if I open the SQL database in an external tool, sqlliteviewer for example, make no changes, and save a copy which I then try to load into sparta. May be related?

**Comment by st3r30byt3** [comment]
Closing a few years later. Hopefully resolved itself? If not, let's reopen
