### ISSUE TITLE
problem importing module

### ISSUE THREAD

**Issue by ssh30** [SECFORCE/sparta#47]
im tryng to launch sparta but it shows me this error.

[-] Import failed. PyQt4 library not found. 
Try installing it with: apt-get install python-qt4

I know there is a message on a try: inside the script but the problem is that i have the PyQt4 module installed, because im able to import the module from the python interpreter

any idea how i can fix this problem?

**Comment by st3r30byt3** [comment]
Hi ssh30. 

Your best bet would be using the latest version of Kali which already has SPARTA and all its dependencies installed. If you would still prefer not to, the best option would be to check this Issue tracker as many people have run into this kind of problem before.

Let us know if you still can't find a solution and in that case, please provide more information to help us help you.

**Comment by faisalbukhari07** [comment]
I have the same problem.
I have just done update, upgrade and dist-upgrade on Kali Linux and it throws this;

root@Tester:~# sparta 
[-] Import failed. PyQt4 library not found. 
Try installing it with: apt-get install python-qt4

but when i tried to install PyQT4 it showed me that its newest version is installed;

root@Tester:~# apt-get install python-qt4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-qt4 is already the newest version (4.11.4+dfsg-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

my Linux kernal is;

root@Tester:~# uname -a
Linux Tester 4.5.0-kali1-amd64 #1 SMP Debian 4.5.3-2kali1 (2016-05-09) x86_64 GNU/Linux


please help me out :(

**Comment by OscarAkaElvis** [comment]
same problem here... it seems with some updates on kale 2016.1 , now there is some kind of dependency problem. I already have the system fully updated with apt-get update and apt-get dist-upgrade.

**Comment by st3r30byt3** [comment]
Hi, please check the fix here:
https://github.com/SECFORCE/sparta/issues/59

**Comment by peterpt** [comment]
**Best way to solve this issue : 
add debian jessie repository to your sources.list**
"deb  http://deb.debian.org/debian jessie main contrib non-free"
"deb-src  http://deb.debian.org/debian jessie main contrib non-free"

apt-get update && apt-get remove --purge python-qt4 python-sip -y && apt-get autoremove
aptitude install python-qt4=4.11.2+dfsg-1 -y && aptitude hold python-qt4 && aptitude hold python-sip 

**To unhold those packages in future and upgrade them do :** 

aptitude unhold python-qt4 && aptitude unhold python-sip && apt-get upgrade

**Comment by st3r30byt3** [comment]
This should be fixed in the latest commit. Thanks for the report.
