### ISSUE TITLE
Adding new tools into Sparta

### ISSUE THREAD

**Issue by xDjPinkiePie** [SECFORCE/sparta#48]
"At the moment, SPARTA can be configured by editing the sparta.conf file located in SPARTA’s root folder. At launch time, SPARTA checks if this file exists and if it does not, a new file is created with default values."

As quoted from your website. Is it possible to add tools into Sparta, such as Sqlmap, or wapiti, so that once the nmap scan is complete, sparta would then run tools like nikto, and wapiti together to scan port 80. If so, what codes should I edit to make this possible?

**Comment by st3r30byt3** [comment]
Hi! Probably it's best that you refer to the documentation link below. It contains an example of setting up the tool Nikto.

http://sparta.secforce.com/documentation/

Let us know if this helps.
