### ISSUE TITLE
SQL Alchemy

### ISSUE THREAD

**Issue by Ne0nd0g** [SECFORCE/sparta#5]
On a fully upgraded version of Kali, I get the following error when trying to run Sparta:

[-] Import failed. Elixir library not found. 
Try installing it with: apt-get install python-elixir

I tried to do the import manually from a Python prompt and get the following:
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import elixir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/pymodules/python2.7/elixir/__init__.py", line 29, in <module>
    from elixir.entity import Entity, EntityBase, EntityMeta, EntityDescriptor, \
  File "/usr/lib/pymodules/python2.7/elixir/entity.py", line 17, in <module>
    from sqlalchemy.orm import MapperExtension, mapper, object_session, \
ImportError: cannot import name ScopedSession

I placed this code right before "import elixir" in the try statement to resolve the issue:
     import sqlalchemy.orm
     sqlalchemy.orm.ScopedSession = sqlalchemy.orm.scoped_session
REF: http://stackoverflow.com/questions/14201210/impossible-to-initialize-elixir

Installed SQLAlchemy version:

dpkg -s python-sqlalchemy
Package: python-sqlalchemy
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 3028
Maintainer: Piotr Ożarowski <piotr@debian.org>
Architecture: all
Source: sqlalchemy
Version: 0.7.8-1

**Comment by st3r30byt3** [comment]
Hi Ne0nd0g. There is no need to import elixir from a python terminal. In Kali all you need to do to install elixir is type this in a terminal:
apt-get install python-elixir

Do let us know if you still have problems after running this command.

**Comment by Ne0nd0g** [comment]
Yes, I understand that. The only reason I attempted to import elixir from a python terminal was to get the error message. Elixir was already installed on host prior to getting the error from Sparta. The try statement in Sparta just catches all exceptions and then reports that elixir is not installed. However, elixir was installed on my system but the code didn't catch my ImportError exception.

**Comment by st3r30byt3** [comment]
I see. Most of our tests were conducted on python 2.7.3, python-elixir 0.7.1-1 and sqlalchemy 0.7.8-1 which are the default versions installed when using apt-get. Those seem to be the same versions (not sure about your elixir version) you are using so I am not sure what is causing the problem. We have tried it on several fresh installs of the newest Kali (32 and 64) and it has worked every time. This is not something we can fix in our code as it seems to be related to your installation of elixir. Nevertheless, we are happy to help if you can provide any more details so that we can replicate the issue.

**Comment by st3r30byt3** [comment]
The fix was in the first post. My bad! :) Thanks for sharing!

**Comment by Cnlouds** [comment]
I got the same problem
Kali latest version installed python 2.7.8-2.
But the python-elixir  depends with python 2.7.3.
So get the following error.
```
root@kali:/usr/share/sparta# apt-get build-dep python-elixir
Reading package lists ... Done
Is analyzing dependency tree package
Reading state information ... Done
Select elixir rather than as a source code package python-elixir
The following packages have unmet dependencies:
  python-all: dependence: python (= 2.7.3-4 + deb7u1) but 2.7.8-2 about to be installed
E: can not meet the build dependencies package python-elixir required.
```
How do i solve the problem in addition to reload the low version of  python?

**Comment by st3r30byt3** [comment]
If I'm not mistaken, python 2.7.3 is the default version in the latest Kali and is the one we used in our tests. We are investigating into the issue but I'd recommend using that version if possible for the time being.

**Comment by craiglawson** [comment]
Hi,

I'm seeing this issue too, I have a standard Kali x64 install:

Python 2.7.3 installed, python-elixir installed

[-] Import failed. Elixir library not found
Try installing it with: apt-get install python-elixir

**Comment by st3r30byt3** [comment]
Hi Craig! Can you check what versions of elixir/sqlalchemy you are using? Also, do you have any other version of python installed which may be the one running? Any other info/configuration which may help us replicate the issue?

**Comment by craiglawson** [comment]
root@kali:~# python -V
Python 2.7.3

root@kali:~# dpkg -s python-elixir
Package: python-elixir
Status: install ok installed
...
Version: 0.7.1-1
...

root@kali:~# uname -a
Linux kali 3.14-kali-amd64 #1 SMP Debian 3.14.5-1kali1 (2014-06-07) x86_64 GNU/Linux

Is there anything else I can provide for you to help diagnose the issue?

**Comment by st3r30byt3** [comment]
It seems like you have all the right versions. Can you check that the version of sqlalchemy is 0.7.8-1? Can you tell us how you are launching SPARTA? Can you provide the terminal output of the following?

root@kali:~# python
>>> import elixir

Thanks!

**Comment by craiglawson** [comment]
root@kali:~# dpkg -s python-sqlalchemy
...
Version: 0.7.8-1
...

root@kali:~# python
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import elixir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/pymodules/python2.7/elixir/__init__.py", line 29, in <module>
    from elixir.entity import Entity, EntityBase, EntityMeta, EntityDescriptor, \
  File "/usr/lib/pymodules/python2.7/elixir/entity.py", line 17, in <module>
    from sqlalchemy.orm import MapperExtension, mapper, object_session, \
ImportError: cannot import name ScopedSession

**Comment by craiglawson** [comment]
I'm launching as per install instructions in README.md (I actually read them - Albeit after I couldn't get it working first time round..!)

**Comment by Ne0nd0g** [comment]
@craiglawson did you try adding the code below right before the "import elixir" statement in sparta.py as a work around?

sqlalchemy.orm.ScopedSession = sqlalchemy.orm.scoped_session

**Comment by craiglawson** [comment]
Just tried that:

```
root@kali:~# sparta
Traceback (most recent call last):
  File "sparta.py", line 14, in <module>
    sqlalchemy.orm.ScopedSession = sqlalchemy.orm.scoped_session
NameError: name 'sqlalchemy' is not defined
```

**Comment by Ne0nd0g** [comment]
What is the output of this:

dpkg -s python-sqlalchemy

**Comment by craiglawson** [comment]
Full output excluding Description info:

```
root@kali:~# dpkg -s python-sqlalchemy
Package: python-sqlalchemy
Status: install ok installed
Priority: optional
Section: python
Installed-Size: 3028
Maintainer: Piotr Ożarowski <piotr@debian.org>
Architecture: all
Source: sqlalchemy
Version: 0.7.8-1
Depends: python2.7 | python2.6, python (>= 2.6.6-7~), python (<< 2.8)
Recommends: python-sqlalchemy-ext
Suggests: python-sqlalchemy-doc, python-psycopg2, python-mysqldb (>= 1.2.1-p2-2), python-kinterbasdb (>= 3.1.2-0.3), python-pymssql
```

**Comment by Ne0nd0g** [comment]
try adding "import sqlalchemy.orm" before the "sqlalchemy.orm.ScopedSession = sqlalchemy.orm.scoped_session" so that your sparta.py file looks like this

```
try:
        import sqlalchemy.orm
        sqlalchemy.orm.ScopedSession = sqlalchemy.orm.scoped_session
        import elixir
except:
        print "[-] Import failed. Elixir library not found. \nTry installing it with: apt-get install python-elixir"
        exit(0)
try:
        from PyQt4 import QtGui, QtCore, QtWebKit
except:
        print "[-] Import failed. PyQt4 library not found. \nTry installing it with: apt-get install python-qt4"
        exit(0)
```

**Comment by craiglawson** [comment]
Perfect - that fixed it! Thanks for your help

C

**Comment by st3r30byt3** [comment]
Thanks Ne0nd0g. We'll add this to a FAQ at some point. :)

**Comment by mcjon3z** [comment]
I ran into this same issue on one of my scripts. Problem that I ran into was that if you put the fix Ne0nd0g mentions above in the source code, then it stops working for users that have the older version of SQLAlchemy. This is what I came up with - appears to allow the code to function no matter which version of SQLAlchemy you have:

```
try:
    # fix SQLAlchemy version issue with Elixir - 0.8 changed location of ScopedSession
    #http://stackoverflow.com/questions/14201210/impossible-to-initialize-elixir
    from sqlalchemy.orm import scoped_session as ScopedSession
except:
    # have correct version - keep on rolling
    pass

try:  
    from elixir import metadata, using_options, Entity, Field
    from elixir import create_all, setup_all, session
    from elixir import Unicode, UnicodeText, Integer, String, BLOB
    from elixir import OneToMany, ManyToMany, ManyToOne, OneToOne
except:
    print "[-] Import failed. Elixir library not found. \nTry installing it with: apt-get install python-elixir"
    exit(0)
```

**Comment by n1h4x** [comment]
any fix for newer python versions? I get 

apt install python-elixir
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-elixir is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

**Comment by st3r30byt3** [comment]
Yes, you can grab the version from the dev branch if you want.

It supports the latest python and doesn't use Elixir anymore. It's under testing from us and hopefully the community :)

If you do use it, let us know of any problems.
