### ISSUE TITLE
list of provided variables for adding tools

### ISSUE THREAD

**Issue by abreksa4** [SECFORCE/sparta#50]
On the [Sparta documentation page](http://sparta.secforce.com/documentation/), you use this as an example for adding tools to Sparta: 
```
nikto=Run nikto, nikto -o [OUTPUT].txt -p [PORT] -h [IP], “http,https”
```

Are there any available variables other than `IP`, `OUTPUT`, and `PORT`? A list would be great in the documentation.

**Comment by st3r30byt3** [comment]
Hi! Sorry for the late reply. For now, there are no other variables other than the ones used in the sparta.conf file. If you feel a particular variable or setting would be useful, don't hesitate to give us some feedback. Cheers
