### ISSUE TITLE
Addition of map tab to include stdout

### ISSUE THREAD

**Issue by phillips321** [SECFORCE/sparta#51]
Please can we enable the tab view of nmap scans? The reason for this is that when scanning if a scan is taking a considerable time we would be able to terminate it. Currently there is no ability to know if a scan has 2 minutes left or 2 hours left.

I think this code is the bit that prevents them from being displayed. controller.py:
if 'nmap' in name:	# to make sure different nmap scans appear under the same tool name
	name = 'nmap'
	invisibleTab = True	

When changed to false they appear briefly and then disappear.

**Comment by st3r30byt3** [comment]
Thanks. We replied in the other post and will leave that one open.
