### ISSUE TITLE
custom nmap scans

### ISSUE THREAD

**Issue by diodepack** [SECFORCE/sparta#52]
would like to see some way of customizing nmap scans / nse scripts

**Comment by st3r30byt3** [comment]
Hi again :)
This is already possible by editing the sparta.conf file as explained in the documentation and in other issues submitted here. We are close to finishing a settings menu which will make the process of customising commands a lot easier.

**Comment by diodepack** [comment]
ok great. the settings menu is actually EXACTLY the sort of implementation i was looking for!
