### ISSUE TITLE
hostnames in addition to ip addresses

### ISSUE THREAD

**Issue by diodepack** [SECFORCE/sparta#53]
would very much like to add host names next to ip addresses similar to the way db_nmap auto-populates the database after running a nmap dns host enumeration nse script against a dns server.

**Comment by st3r30byt3** [comment]
Hi diodepack. Thanks for the feedback.
We are not sure we understand. Hostnames are already being displayed (assuming your nmap command does DNS resolution).

**Comment by diodepack** [comment]
interesting. let me look into it.

**Comment by diodepack** [comment]
figured it out: had to define a local DNS server to resolve hostnames

**Comment by diodepack** [comment]
it would be nice to have a menu option to define a local dns server or similar function so testers don't have to edit sparta.conf for every new network.
