### ISSUE TITLE
enhancement: select more than one host at a time

### ISSUE THREAD

**Issue by diodepack** [SECFORCE/sparta#54]
it would be nice to allow users to select more than one host at a time.

for some non-staged (yet still intensive scans) it would be nice to queue more than one scan at a time.

**Comment by st3r30byt3** [comment]
Hi again.

There is another thread regarding your first point, so I'll close this one.

Regarding your second point, I am not sure to follow. You can already queue tools by means of the scheduler or staged nmap. If you want one scan to happen at a time you can also limit the number of processes to 1 for example. Dirty hack but it would work. :)
