### ISSUE TITLE
Calls snmpcheck with snmp-check command line

### ISSUE THREAD

**Issue by oM3fC** [SECFORCE/sparta#55]
The snmp-check command line needs to be corrected. Currently, it results in a pile of inactive GUI snmpcheck windows popping up instead of correctly calling snmp-check and importing results back into the Sparta interface.

snmpcheck -t [ip] [port]

should be

snmp-check -t [ip] [port]

**Comment by st3r30byt3** [comment]
Thanks for this. We have fixed it and the change will be released with the next version.

**Comment by Kaicastledine** [comment]
when will this fix/release be released do you know ?

**Comment by st3r30byt3** [comment]
Unfortunately we have had very little time to work on SPARTA given that we are full-time penetration testers. We plan to release a new version some time this year but do not know exactly when.

In the meantime, the easiest thing to do is to edit the configuration file (sparta.conf) and change the command. In general, you can also add/remove tools quite easily. If you are unsure how to do that just check our documentation on the website.

**Comment by Kaicastledine** [comment]
No worries thought I'd ask to see what's in the pipeline for this program as its a very nice tool indeed.

Kind regards 

    On Tuesday, 5 April 2016, 12:03, Antonio Quina <notifications@github.com> wrote:
 

 Unfortunately we have had very little time to work on SPARTA given that we are full-time penetration testers. We plan to release a new version some time this year but do not know exactly when.In the meantime, the easiest thing to do is to edit the configuration file (sparta.conf) and change the command. In general, you can also add/remove tools quite easily. If you are unsure how to do that just check our documentation on the website.—

**Comment by zinkwazi** [comment]
Hi, we were having the same issue and updated /etc/sparta.conf as follows:

snmpcheck=Run snmpcheck, snmp-check [IP], "snmp,snmptrap"

Note that in addition to the change recommended by @oM3fC , we also had to remove the -t to make it work.  If you want to change the timeout from the default of 5 seconds then you'd need to add that after the -t (e.g. 7 seconds) like this:
snmpcheck=Run snmpcheck, snmp-check -t 7 [IP], "snmp,snmptrap"

Great tool, thanks all!
