### ISSUE TITLE
Issue with Hydra default scans

### ISSUE THREAD

**Issue by Kaicastledine** [SECFORCE/sparta#57]
Hello

When trying to check for default FTP or any service hydra produces this error.

[ERROR] file for colon files (login:pass) not found:./wordlists/ftp-default-userpass.txt

Not sure what broke this as was working fine earlier, potential update broke feature.

Running of kali linux, Opened sparta from usr/share/sparta  - issue still persent
Copied sparta wordlists to Kalis wordlist location - issue still present 

Not sure why the app cannot find the wordlists, any ideas ?

Kind regards

**Comment by Kaicastledine** [comment]
This also happens with the other default bruteforcers

I've checked in the sparta data location and the word lists are there 

The sparta config how ever points to /usr/share/wordlists    - not sure if this is meant to point to the spartas wordlist location instead of the one built into kali

**Comment by st3r30byt3** [comment]
Hi! We have not updated SPARTA recently and the configuration file should be pointing to the correct files, under ./wordlists/. It could be that your conf file is broken for some reason. Could you copy-paste the relevant lines from sparta.conf?

What version of Kali / hydra do you have?

**Comment by Kaicastledine** [comment]
Hello

Under brute settings  here are the two paths
username-wordlist-path=/usr/share/wordlists/password-wordlist-path=usr/share/wordlists/
We recently tested the new PTF by trusted Sec which has overwritten hydra - not sure if this has broken it.

Kind regards 

    On Monday, 4 April 2016, 15:03, Antonio Quina <notifications@github.com> wrote:
 

 Hi! We have not updated SPARTA recently and the configuration file should be pointing to the correct files, under ./wordlists/. It could be that your conf file is broken for some reason. Could you copy-paste the relevant lines from sparta.conf?What version of Kali / hydra do you have?—

**Comment by st3r30byt3** [comment]
Hey again.

Those are the paths used by the Brute tab. They are not related to the default credentials checks.
Look for "ftp-default" in sparta.conf and let us know what command is there.

If you have overwritten hydra on your system, for sure SPARTA will be broken :) You need hydra on your system. You can always try to troubleshoot the commands present in sparta.conf by running them from a terminal.

Let us know how it goes!

**Comment by Kaicastledine** [comment]
Yes sorry here you go,




Hydra still works as normal working and tested so that I dont think is the issue.
Kind regards 

    On Monday, 4 April 2016, 15:25, Antonio Quina <notifications@github.com> wrote:
 

 Hey again.Those are the paths used by the Brute tab. They are not related to the default credentials checks.
Look for "ftp-default" in sparta.conf and let us know what command is there.If you have overwritten hydra on your system, for sure SPARTA will be broken :) You need hydra on your system. You can always try to troubleshoot the commands present in sparta.conf by running them from a terminal.Let us know how it goes!—

**Comment by st3r30byt3** [comment]
Good. Thanks. Can you look for "ftp-default" in sparta.conf and let us know what command is there?

**Comment by Kaicastledine** [comment]
Ah hold on the Image got stripped out via email

![image](https://cloud.githubusercontent.com/assets/11678433/14251610/b7cc09ba-fa7b-11e5-9a1b-727af5d2feb5.png)

Just added it back in via Githhub

**Comment by st3r30byt3** [comment]
Hmm. The command is correct, the wordlists are correct and you mentioned that hydra is working as expected.

What version of Kali, hydra and SPARTA are you running?
How are you launching SPARTA?

Can you try running the following command from a terminal (inside /usr/share/sparta) on the same host/port you were trying to attack and let us know the output? (obfuscate the host/IP if necessary)

hydra -s <port> -C ./wordlists/ftp-default-userpass.txt -u -f <host> ftp

**Comment by Kaicastledine** [comment]
Its kali 2 - Will grab ver in a min
Both from the launcher and terminal 

Sparta ver: 1.0.2 
Hydra ver: 8.2-dev

![image](https://cloud.githubusercontent.com/assets/11678433/14253678/5f542692-fa84-11e5-84eb-33fb096b3166.png)

When using xhydra it works - shown in the background

**Comment by Kaicastledine** [comment]
Just opened up an old project - which has default checkers with working results and that does not work either.

Could this be hydra thats the issue ? Not sure if this has been caused by PTF moving the install location of Hydra ( Only a theory because it could of not touched it at all)

**Comment by st3r30byt3** [comment]
Hi! Hydra is definitely the issue. The proof being that when you run the command outside of SPARTA, it still doesn't work. It also seems that it was compiled without SSL support so that will also cause trouble for some services (not for ftp).

The default version of hydra in Kali 2.0 is 8.1. What you can do is check what command line arguments this version of Hydra expects and then once you make it work in a terminal just replace the command in sparta.conf. Everything should work then.

Hope this helps. Will close this issue given that it's not a SPARTA bug.
