### ISSUE TITLE
Failed to make screenshots with https 

### ISSUE THREAD

**Issue by lobeznorx** [SECFORCE/sparta#58]
Hi,

When you try to screenshots, assign an IP port 443 which makes when performing capture not appear correctly. Catches should do before putting https: //

I hope I explained correctly.

Grettings

**Comment by lenlorijn** [comment]
Hi lobeznorx,

The current readme states that this is a known issue. Have you looked to see if the solution mentioned in the readme fixes the issue for you?

By the way I'm not a maintainer or contributor of this repository, but I saw your question and thought this might be helpful.

**Comment by st3r30byt3** [comment]
Hi lobeznorx. Exactly what lenlorijn wrote (thanks)! :) 

I'll close this because it is almost surely the same issue but feel free to post additional details if necessary.
