### ISSUE TITLE
Where are port actions for nmap scripts defined

### ISSUE THREAD

**Issue by dmittakarin8** [SECFORCE/sparta#62]
Where are the nmap scripts defined per port?  For example, if I want to run nmap scripts on port 80, I see in sparta that the 'http-methods' and 'http-title' scripts were executed.  I'd like to redefine this rule to execute all http nse scripts (http-*).  Where is it defined to execute http-methods and http-title nse scripts for port 80?  I did not see the ability to define this in the sparta.conf file.

**Comment by st3r30byt3** [comment]
Hi! When you right-click and run nmap scripts on a port, it is only running the scripts that run by default in nmap. This is why you cannot find them defined in the conf.

You can always edit sparta.conf to add a new command under port actions. Just specify the scripts you want to run using nmap's --script option.
