### ISSUE TITLE
sslscan options (--xml & --no-colour)

### ISSUE THREAD

**Issue by HanseSecure** [SECFORCE/sparta#67]
Hi,

1. there are no output files after my sslscan. I added following lines in my sparta.conf (The scan is running and the results are shown in my sslscan-Tab :-( : 

[ToolSettings]
sslscan-path=/usr/bin/sslscan
[PortActions]
sslscan= RUN sslcan, sslcan --no-colour --xml \"[OUTPUT]\" [IP]:[PORT], "https,ssl,ms-wbt-server,imap,pop3,smtp"
[SchedulerSettings]
sslscan="https,ssl,ms-wbt-server,imap,pop3,smtp", tcp

2. I decided to set the no-colour flag in sslscan to solve badCharacters in the Sparta-Gui, but the no-colour flag doesnt trigger.

My System is a Kali-VM 64Bit.

Best Regards,

Flo

**Comment by st3r30byt3** [comment]
Hi Flo,

If you check other commands in the sparta.conf file, you'll notice that the double quotes around [OUTPUT] are usually escaped with \

Have you tried that?

**Comment by st3r30byt3** [comment]
Closing due to lack of details.
