### ISSUE TITLE
implement new feature

### ISSUE THREAD

**Issue by peterpt** [SECFORCE/sparta#68]
IT could be interesting if wafw00f was implemented in sparta .
with wafwoof sparta can fingerprint witch firewall type is protecting the current website/server .
https://github.com/EnableSecurity/wafw00f

**Comment by st3r30byt3** [comment]
The great thing about SPARTA is that anyone can add tools/features so that it uses YOUR toolkit! At the moment this can be done via the sparta.conf file.
