### ISSUE TITLE
QtWebKit

### ISSUE THREAD

**Issue by adamziaja** [SECFORCE/sparta#69]
There is no QtWebKit in PyQt4 in Ubuntu/Debian systems.

**Comment by st3r30byt3** [comment]
Hi! We mostly focus on getting SPARTA working in Kali Linux. We do think that we will eventually need to replace QtWebKit with a better alternative because it has caused problems even in Kali in the past.

**Comment by st3r30byt3** [comment]
This should be fixed in the latest commit. Thanks for the report. Thanks alexxn for the fix.
