### ISSUE TITLE
Question: Command Line or API function.

### ISSUE THREAD

**Issue by ggtd** [SECFORCE/sparta#74]
**Sparta is cool! I have a question:** Is it possible to run Sparta then initiate Scan from CLI/Commandline or Python function. Then save the scan results to file?  

Anyone have some TIP how to automate scans using some interface or via commandline.

Thanks.
t.

**Comment by Ch4p34uN0iR** [comment]
Sparta is AWESOME. It would be nice if we could import more than one nmap xml at once. Perhaps from the command line at least.
