### ISSUE TITLE
ms08-067_check

### ISSUE THREAD

**Issue by chris948** [SECFORCE/sparta#79]
I realize that this isn't really sparta, just a script that sparta comes with, but it doesn't work with new Kali installs, impacket was updated.

I'm not any good at this, but I think if anyone is searching for why that script is broken

ms08-067_check.py
    from impacket.dcerpc import dcerpc
    from impacket.dcerpc import transport

should be
    from impacket.dcerpc.v5 import rpcrt
    from impacket.dcerpc.v5 import transport

**Comment by st3r30byt3** [comment]
Fixed in the latest commit. Thanks for the report.
