### ISSUE TITLE
Sorting by Status in log does not function as expected

### ISSUE THREAD

**Issue by ad0nis** [SECFORCE/sparta#8]
If you click on the status column, the expected behavior would be to sort by that column. Within one or two clicks, it should be possible to bring tasks that are still running to the top of the log.

There should also be an End Time for each task, but I guess that's more of a separate feature request...

**Comment by st3r30byt3** [comment]
Hey ad0nis! Thanks for the bug report and the feature request. We'll look into it shortly.

**Comment by FraPalazzo** [comment]
Hello,
I agree with ad0nis about his request to implement the "End Time" for each task. It could be useful to identify some DoS or other problems that could happen during/after a scan.

Thank you.

**Comment by st3r30byt3** [comment]
The "end time" column has been added to the next commit. Thx
