### ISSUE TITLE
Kali Linux Rolling Release Sparta PyQt4 Library Not Found

### ISSUE THREAD

**Issue by ahusmc** [SECFORCE/sparta#83]
Hello:

As of 16 Dec 2017, Sparta on Kali Linux rolling release, the PyQt4 library will not import and Sparta will not start.  (PyQt4 installed as of latest update = 4.12.1+dfsg-2

Referenced Issue: https://github.com/SECFORCE/sparta/issues/59

I use Sparta extensively for my research and wanted to reach out and see what we can do. Associated details as follow:

root@KL-1:~# sparta
[-] Import failed. PyQt4 library not found. 
Try installing it with: apt-get install python-qt4
root@KL-1:~# hostnamectl 
   Static hostname: KL-1
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ####
           Boot ID: ####
    Virtualization: oracle
  Operating System: Kali GNU/Linux Rolling
            Kernel: Linux 4.14.0-kali1-amd64
      Architecture: x86-64
root@KL-1:~# uname -a
Linux KL-1 4.14.0-kali1-amd64 #1 SMP Debian 4.14.2-1kali1 (2017-12-04) x86_64 GNU/Linux
root@KL-1:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	kali-rolling
Codename:	kali-rolling

root@KL-1:~#  apt-get install python-qt4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-qt4 is already the newest version (4.12.1+dfsg-2).
python-qt4 set to manually installed.

**Comment by aungpyaythar1999** [comment]
I have the same problem here, mate. 
It seems they don't fix it yet.

**Comment by mrosenhahn** [comment]
I ran into this issue as well.
This seems to be a recurring issue and I found a temporary fix in an earlier occurrence of this issue.

https://github.com/SECFORCE/sparta/issues/59

And here

https://stackoverflow.com/questions/37604532/python-2-7-11-importerror-cannot-import-name-qtwebkit-kali-linux-debian-8

The edits were easy enough to do and I was able to get Sparta working again after making them. But the next time you update Kali you will probably be needing to go back and make the fix again

**Comment by ahusmc** [comment]
@mrosenhahn 

It appears that the fix detailed in the link no longer functions on the latest version of Kali Linux. Thanks for the help. Hopefully, SECFORCE will issue a fix.

**Comment by security-consultant** [comment]
Any update on this? Used to be a good tool, please fix.

**Comment by ahusmc** [comment]
Looks like Sparta is done.

**Comment by jasnow** [comment]
Still a problem

**Comment by st3r30byt3** [comment]
This should be fixed in the latest commit. Thanks for the report. Thanks alexxn for the fix.

**Comment by ahusmc** [comment]
Thanks @alexxn

**Comment by us3rnf** [comment]
just use "sudo legion", it has been update, its not sparta anymore
