### ISSUE TITLE
missing and future git tags

### ISSUE THREAD

**Issue by anthraxx** [SECFORCE/sparta#85]
Hi,
it looks like 1.0.2 and 1.0.3 git tags were missing, can you please create and push them plus possible do so in future releases?
Thanks a lot!

**Comment by st3r30byt3** [comment]
We created the git tag for the latest release. Won't be doing it for previous ones, since there isn't much point in using them. Thanks!

**Comment by anthraxx** [comment]
Thanks, works for me. Just interested in the most current and future tags :cat:
