### ISSUE TITLE
Automatic scan with xml output

### ISSUE THREAD

**Issue by cpandya2909** [SECFORCE/sparta#91]
I really appreciate this tool and have been using it for a long time and it has helped me many many times.

The feature which I like most is the stage-wise different scans but the only problem is, I can not automate this for periodic scans.

Can you provide a command line option to give a list of targets and write output in XML format?

**Comment by st3r30byt3** [comment]
Hi! Thanks for the feedback!

What do you mean by periodic scans? As in, scanning automatically every few days, or something?

We can definitely create a command line option to provide a target range / targets file. 

Regarding the output, what do you mean exactly? There have been requests for some sort of reporting. Is this what you mean?

**Comment by cpandya2909** [comment]
I have created a tool which scans targeted ips each day and perform various checks.

I would like to run sparta from command line with target list 
something like "sparta -l <file with ips to scan> / sparta -t <target host to scan>"

also. To see the result of the scan, it sparta can generate some kind of parsable output. like in xml or json then it will be dam cool.

**Comment by st3r30byt3** [comment]
If you check the dev branch, we just pushed the -t command line option where you can specify a target IP range.

What kind of output are you expecting from sparta? All tool output should be saved in sparta's project folder.

**Comment by st3r30byt3** [comment]
Closed for lack of input.
