### ISSUE TITLE
Broken GUI

### ISSUE THREAD

**Issue by MKRG91** [SECFORCE/sparta#92]
I face a problem with the gui of the tool . The thing is , its running and all but all the options of the gui are shown in symbols and icons . Is there someone that had the same issue?Any suggested tweaks to fix this?

**Comment by st3r30byt3** [comment]
Hi. Sorry for the very late reply. Do you have any other details you could share? Maybe about your environment or a screenshot?

**Comment by MKRG91** [comment]
Hi there,

I made a fresh install of Kali and now it's working perfectly fine. I guess my version of OS was deprecated or got messed up with some unstable updates but anyways, thanks for the response.
________________________________

**Comment by MKRG91** [comment]
I made a fresh install of Kali and now it's working perfectly fine. I guess my version of OS was deprecated or got messed up with an unstable update but anyways thanks for the response.

**Comment by st3r30byt3** [comment]
Ok, good to hear. Again, sorry for the late reply. Closing
