### ISSUE TITLE
Stage 1 crash - Premature end of data in tag nmaprun line 5

### ISSUE THREAD

**Issue by farkusza** [SECFORCE/sparta#93]
Hi i'm getting this error when running a scan on any network. Tested on other machines and it is working.

Logs in the console window show as below:
[+] Wordlist was created/opened: /tmp/sparta-TEHJhS-tool-output/sparta-passwords.txt
[+] Loading settings file..
[+] Process killed!
/tmp/sparta-Ne9pRo-running/nmap/20181212022856-nmapstage1.xml:8: parser error : Premature end of data in tag nmaprun line 5

^
cannot parse /tmp/sparta-Ne9pRo-running/nmap/20181212022856-nmapstage1.xml
[+] Parsing nmap xml file: /tmp/sparta-TEHJhS-tool-output/nmap/20181212022856-nmapstage1.xml
	[-] Parser error! Invalid nmap file!
	[-] Giving up on import due to previous errors.
	[-] Unexpected error: <class 'xml.parsers.expat.ExpatError'>
	[+] The process is done!

**Comment by st3r30byt3** [comment]
Hi there! Are you running this from the latest Kali?
Can you provide more details about your environment?

**Comment by st3r30byt3** [comment]
Closing for lack of info.
