### ISSUE TITLE
Pyside is deprecated in favor of Pyside2

### ISSUE THREAD

**Issue by rhertzog** [SECFORCE/sparta#94]
sparta relies on PySide.QtWebKit but PySide is deprecated in favor of PySide2 (https://wiki.qt.io/Qt_for_Python). You should consider switching to PySide2.

PySide2 provides PySide2.QtWebEngineCore and  PySide2.QtWebEngineWidgets which hopefully provides similar functionalities to PySide.QtWebKit.

https://doc.qt.io/qtforpython/PySide2/QtWebEngineWidgets/index.html
https://doc.qt.io/qtforpython/PySide2/QtWebEngineCore/index.html
http://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html

FWIW, if this issue doesn't get resolved, it seems likely that we will have to drop sparta from Kali Linux.
This is tracked here in the Kali bug tracker: https://bugs.kali.org/view.php?id=4978

Thank you for your work on sparta!

**Comment by st3r30byt3** [comment]
We've ported SPARTA to Python3 and PyQt5. It should run on the latest Kali.

For now it's on the dev branch but we will push to master once more testing has been conducted:
https://github.com/SECFORCE/sparta/tree/dev
