### ISSUE TITLE
GUI doesnt load at all

### ISSUE THREAD

**Issue by R-Gue** [SECFORCE/sparta#98]
So i am on Kali the system and sparta are update. But when starting up i just get a white window and my shell is throwing these errors:

``
[+] Creating temporary files..
[+] Wordlist was created/opened: /tmp/sparta-BQJtGs-tool-output/sparta-usernames.txt
[+] Wordlist was created/opened: /tmp/sparta-BQJtGs-tool-output/sparta-passwords.txt
[+] Loading settings file..
X Error: BadAccess (attempt to access private resource denied) 10
  Extension:    130 (MIT-SHM)
  Minor opcode: 1 (X_ShmAttach)
  Resource id:  0x150
X Error: BadShmSeg (invalid shared segment parameter) 128
  Extension:    130 (MIT-SHM)
  Minor opcode: 5 (X_ShmCreatePixmap)
  Resource id:  0x2800011
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2800012
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2800012
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2800012
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x2800012
``

**Comment by st3r30byt3** [comment]
From the error messages this doesn't seem like a problem with SPARTA. As far as we know, no one else is facing this problem in the latest kali.

Can you provide any more info about your environment?
